In [2]:
import pandas as pd
df=pd.read_csv("car data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [4]:
df.isna().sum()
# data is ok so go ahead

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [5]:
df.drop(columns="Car_Name",inplace=True)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           301 non-null    int64
 1   Selling_Price  301 non-null    float64
 2   Present_Price  301 non-null    float64
 3   Kms_Driven     301 non-null    int64
 4   Fuel_Type      301 non-null    object
 5   Seller_Type    301 non-null    object
 6   Transmission   301 non-null    object
 7   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 18.9+ KB
None

In [6]:
df['age']=2026-df['Year']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           301 non-null    int64
 1   Selling_Price  301 non-null    float64
 2   Present_Price  301 non-null    float64
 3   Kms_Driven     301 non-null    int64
 4   Fuel_Type      301 non-null    object
 5   Seller_Type    301 non-null    object
 6   Transmission   301 non-null    object
 7   Owner          301 non-null    int64
 8   age            301 non-null    int64
dtypes: float64(2), int64(4), object(3)
memory usage: 21.3+ KB

In [7]:
df.drop(columns="Year", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Selling_Price  301 non-null    float64
 1   Present_Price  301 non-null    float64
 2   Kms_Driven     301 non-null    int64
 3   Fuel_Type      301 non-null    object
 4   Seller_Type    301 non-null    object
 5   Transmission   301 non-null    object
 6   Owner          301 non-null    int64
 7   age            301 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 18.9+ KB

In [8]:
df.columns

Index(['Selling_Price', 'Present_Price', 'Kms_Driven', 'Fuel_Type',
       'Seller_Type', 'Transmission', 'Owner', 'age'],
      dtype='object')

In [9]:
df=pd.get_dummies(data=df,drop_first=True)
df.columns

Index(['Selling_Price', 'Present_Price', 'Kms_Driven', 'Owner', 'age',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual',
       'Transmission_Manual'],
      dtype='object')

In [10]:
y=df["Selling_Price"]
x=df.drop(columns="Selling_Price")
print(x.shape)
y.shape

(301, 8)

(301,)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1) 

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
diff=pd.DataFrame({"Actualy":y_test,"Preidct":y_pred})

print("Coeffecitn m : ",lr.coef_)
print("Intercept c : ",lr.intercept_)

from sklearn import metrics
print("\nMAE: ",metrics.mean_absolute_error(y_test,y_pred))
print("MSE: ",metrics.mean_squared_error(y_test,y_pred))
print("R2 Score: ",metrics.r2_score(y_test,y_pred))

Coeffecitn m :  [ 4.37233976e-01 -5.30613944e-06  3.45912849e-01 -4.13270098e-01
  2.23050770e+00  4.58549217e-01 -1.20927814e+00 -1.87014327e+00]
Intercept c :  7.900300130264206

MAE:  1.0998575552990955
MSE:  2.9823848618597513
R2 Score:  0.8625260513315252

In [16]:
# from sklearn.linear_model import LinearRegression
# lr=LinearRegression()
# y_pred=lr.predict([[5.5,25000,0,5,0,1,1,1]])
# y_pred

## Advertising.csv

In [13]:
import pandas as pd
df=pd.read_csv("Advertising.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [17]:
df.isna().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [18]:
y=df["Sales"]
x=df.drop(columns="Sales")
print(x.shape)
y.shape

(200, 4)

(200,)

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
df=pd.DataFrame({"Actual" : y_test,"predict":y_pred})
df

     Actual    predict
58     23.8  21.739938
40     16.6  16.465126
34      9.5   7.671364
102    14.8  17.892926
184    17.6  18.665973
198    25.5  23.846286
95     16.9  16.335154
4      12.9  13.468391
29     10.5   9.186660
168    17.1  17.349559
171    14.5  14.457145
18     11.3   9.869076
11     17.4  17.274399
89     16.7  16.717798
110    13.4  15.092958
118    15.9  15.583111
159    12.9  12.443783
35     12.8  17.290382
136     9.5  11.090161
59     18.4  18.075597
51     10.7   9.343329
16     12.5  12.919064
44      8.5   8.791014
94     11.5  10.469179
31     11.9  11.412206
162    14.9  15.023128
38     10.1   9.792826
28     18.9  19.470464
193    19.6  18.217760
27     15.9  17.206652
47     23.2  21.610282
165    11.9  14.707567
194    17.3  16.280251
177    11.7  12.354188
176    20.2  19.978303
97     15.5  15.376629
174    11.5  13.958656
73     11.0  10.072501
69     22.3  20.975549
172     7.6   7.449935

In [24]:
print("Coeffiecet m: ",lr.coef_)
print("Intercept c: ",lr.intercept_)

Coeffiecet m:  [-1.36610117e-04  4.68432118e-02  1.78501247e-01  2.52272234e-03]
Intercept c:  2.9246804226395344

In [27]:
from sklearn import metrics
print("MAE : ",metrics.mean_absolute_error(y_test,y_pred))
print("MSE : ",metrics.mean_squared_error(y_test,y_pred))
print("R2 : ",metrics.r2_score(y_test,y_pred)) # nearby 1 artle model saru kebvay 😁😁😁

MAE :  1.0393122952652356
MSE :  1.9897012313285765
R2 :  0.8928781912093182

## FuelConsumptionCo2.csv

In [31]:
import pandas as pd
df=pd.read_csv("FuelConsumptionCo2.csv")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   MODELYEAR                 1067 non-null   int64
 1   MAKE                      1067 non-null   object
 2   MODEL                     1067 non-null   object
 3   VEHICLECLASS              1067 non-null   object
 4   ENGINESIZE                1067 non-null   float64
 5   CYLINDERS                 1067 non-null   int64
 6   TRANSMISSION              1067 non-null   object
 7   FUELTYPE                  1067 non-null   object
 8   FUELCONSUMPTION_CITY      1067 non-null   float64
 9   FUELCONSUMPTION_HWY       1067 non-null   float64
 10  FUELCONSUMPTION_COMB      1067 non-null   float64
 11  FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 12  CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(4), object(5)
memory usage: 108.5+ KB

In [36]:
df.drop(columns=["MAKE","MAKE","VEHICLECLASS",'TRANSMISSION'],inplace=True)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   MODELYEAR                 1067 non-null   int64
 1   MODEL                     1067 non-null   object
 2   ENGINESIZE                1067 non-null   float64
 3   CYLINDERS                 1067 non-null   int64
 4   FUELTYPE                  1067 non-null   object
 5   FUELCONSUMPTION_CITY      1067 non-null   float64
 6   FUELCONSUMPTION_HWY       1067 non-null   float64
 7   FUELCONSUMPTION_COMB      1067 non-null   float64
 8   FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 9   CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 83.5+ KB

In [40]:
y=df["CO2EMISSIONS"]
x=df[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_COMB"]]
print(x.shape)
y.shape

(1067, 3)

(1067,)

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
df=pd.DataFrame({"Actual":y_test,"Predict":y_pred})
df

     Actual     Predict
133     274  257.072975
340     200  193.626754
948     196  198.619472
704     161  184.031563
661     320  308.848870
..      ...         ...
961     301  275.681075
523     184  189.131654
884     274  266.323339
8       267  262.249461
415     126  169.443653

[214 rows x 2 columns]

In [52]:
print("Coeffiecet m: ",lr.coef_)
print("Intercept c: ",lr.intercept_)

from sklearn import metrics
print("MEA : ",metrics.mean_absolute_error(y_test,y_pred))
print("MSA : ",metrics.mean_squared_error(y_test,y_pred))
print("R2 : ",metrics.r2_score(y_test,y_pred))

Coeffiecet m:  [11.56295409  6.91231122  9.72527271]
Intercept c:  65.17950048137254
MEA :  16.64682799882323
MSA :  546.2591396903438
R2 :  0.8653355812644816