In [1]:
import requests,json
from bs4 import BeautifulSoup
api="3b5a258fb2bb246eacb62e89cca5fa33"
def get_coordinate():
    api_key=api
    city=input("Enter City :")
    url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api}"
    response=requests.get(url,verify=False)
    coord=response.json()
    print(json.dumps(coord,indent=5))
    return coord
    # url="http://api.openweathermap.org/geo/1.0/direct?q="+city+"&appid={"+api+"}"
a=get_coordinate()

Enter City : ahmedabad

[
     {
          "name": "Ahmedabad",
          "local_names": {
               "ml": "\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d3e\u0d2c\u0d3e\u0d26\u0d4d",
               "ta": "\u0b85\u0b95\u0bae\u0ba4\u0bbe\u0baa\u0bbe\u0ba4\u0bcd",
               "ar": "\u0623\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "de": "Ahmedabad",
               "gu": "\u0a85\u0aae\u0aa6\u0abe\u0ab5\u0abe\u0aa6",
               "ne": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "uk": "\u0410\u0445\u043c\u0435\u0434\u0430\u0431\u0430\u0434",
               "ascii": "Ahmedabad",
               "bn": "\u0986\u09b9\u09ae\u09c7\u09a6\u09be\u09ac\u09be\u09a6",
               "hi": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "eo": "Ahmadabado",
               "te": "\u0c05\u0c39\u0c4d\u0c2e\u0c26\u0c3e\u0c2c\u0c3e\u0c26\u0c4d",
               "feature_name": "Ahmedabad",
               "kn": "\u0c85\u0cb9\u0ccd\u0cae\u0ca6\u0cbe\u0cac\u0cbe\u0ca6\u0ccd",
               "pa": "\u0a05\u0a39\u0a3f\u0a2e\u0a26\u0a3e\u0a2c\u0a3e\u0a26",
               "zh": "\u827e\u54c8\u8fc8\u8fbe\u5df4\u5fb7",
               "ur": "\u0627\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "ja": "\u30a2\u30d5\u30de\u30c0\u30fc\u30d0\u30fc\u30c9",
               "or": "\u0b05\u0b39\u0b2e\u0b26\u0b3e\u0b2c\u0b3e\u0b26",
               "mr": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "pl": "Ahmadabad",
               "oc": "Ahmadabad",
               "cs": "Ahmad\u00e1b\u00e1d",
               "en": "Ahmedabad",
               "he": "\u05d0\u05d7\u05de\u05d3\u05d0\u05d1\u05d0\u05d3",
               "ru": "\u0410\u0445\u043c\u0430\u0434\u0430\u0431\u0430\u0434",
               "tt": "\u04d8\u0445\u043c\u04d9\u0442\u0430\u0431\u0430\u0434"
          },
          "lat": 23.0215374,
          "lon": 72.5800568,
          "country": "IN",
          "state": "Gujarat"
     }
]

In [2]:
y=a[0]["lon"] 
x=a[0]["lat"]

In [3]:
print("Latitude :",x,"Longitude :",y)

Latitude : 23.0215374 Longitude : 72.5800568

In [4]:

import requests,json
from bs4 import BeautifulSoup
api="3b5a258fb2bb246eacb62e89cca5fa33"
def current_weather():
    api_key=api
    url=f"https://api.openweathermap.org/data/2.5/weather?lat={x}&lon={y}&appid={api}"
    response=requests.get(url,verify=False)
    weather=response.json()
    print(json.dumps(weather,indent=5))
    return weather
    # url="http://api.openweathermap.org/geo/1.0/direct?q="+city+"&appid={"+api+"}"
b=current_weather()

{
     "coord": {
          "lon": 72.5797,
          "lat": 23.0216
     },
     "weather": [
          {
               "id": 711,
               "main": "Smoke",
               "description": "smoke",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 308.19,
          "feels_like": 309.86,
          "temp_min": 308.19,
          "temp_max": 308.19,
          "pressure": 1006,
          "humidity": 38,
          "sea_level": 1006,
          "grnd_level": 1001
     },
     "visibility": 5000,
     "wind": {
          "speed": 6.17,
          "deg": 180
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779779989,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779755113,
          "sunset": 1779803309
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}

C:\ProgramData\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.251'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [5]:
decr=b["weather"][0]["description"]
temp=b["main"]["temp"]
pres=b["main"]["pressure"]
humidity=b["main"]["humidity"]
wind_speed=b["wind"]["speed"]
visibility=b["visibility"]

In [6]:
print(f"Weather Description: {decr}")
print(f"Temperature: {temp} Kelvin")
print(f"Atmospheric Pressure: {pres} Hectopascals")
print(f"Humidity: {humidity} Percentage")
print(f"Wind Speed: {wind_speed} Meters per Second")
print(f"Visibility: {visibility} Meters")

Weather Description: smoke
Temperature: 308.19 Kelvin
Atmospheric Pressure: 1006 Hectopascals
Humidity: 38 Percentage
Wind Speed: 6.17 Meters per Second
Visibility: 5000 Meters

# All in one

In [7]:
import requests,json
from bs4 import BeautifulSoup
api="3b5a258fb2bb246eacb62e89cca5fa33"
def current_weather_data():
    api_key=api
    city=input("Enter City :")
    url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api}"
    response=requests.get(url,verify=False)
    coord=response.json()

    y=coord[0]["lon"] 
    x=coord[0]["lat"]
  
    url2=f"https://api.openweathermap.org/data/2.5/weather?lat={x}&lon={y}&appid={api}"
    response2=requests.get(url2,verify=False)
    weather=response2.json()
    print(json.dumps(weather,indent=5))

    d=weather["weather"][0]["description"]
    print(d)
current_weather_data()

Enter City : ahmedabad

{
     "coord": {
          "lon": 72.5797,
          "lat": 23.0216
     },
     "weather": [
          {
               "id": 711,
               "main": "Smoke",
               "description": "smoke",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 308.19,
          "feels_like": 309.86,
          "temp_min": 308.19,
          "temp_max": 308.19,
          "pressure": 1006,
          "humidity": 38,
          "sea_level": 1006,
          "grnd_level": 1001
     },
     "visibility": 5000,
     "wind": {
          "speed": 6.17,
          "deg": 180
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779779989,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779755113,
          "sunset": 1779803309
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}
smoke

C:\ProgramData\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.251'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [8]:
import pandas as pd

headers = ["Qualitative name", "Index", "SO₂", "NO₂", "PM₁₀", "PM₂.₅", "O₃", "CO"]
data = [
    ["Good", 1, "[0; 20)", "[0; 40)", "[0; 20)", "[0; 10)", "[0; 60)", "[0; 4400)"],
    ["Fair", 2, "[20; 80)", "[40; 70)", "[20; 50)", "[10; 25)", "[60; 100)", "[4400; 9400)"],
    ["Moderate", 3, "[80; 250)", "[70; 150)", "[50; 100)", "[25; 50)", "[100; 140)", "[9400; 12400)"],
    ["Poor", 4, "[250; 350)", "[150; 200)", "[100; 200)", "[50; 75)", "[140; 180)", "[12400; 15400)"],
    ["Very Poor", 5, ">350", ">200", ">200", ">75", ">180", ">15400"]
]

df = pd.DataFrame(data, columns=headers)
df

,Qualitative name,Index,SO₂,NO₂,PM₁₀,PM₂.₅,O₃,CO
0,Good,1,[0; 20),[0; 40),[0; 20),[0; 10),[0; 60),[0; 4400)
1,Fair,2,[20; 80),[40; 70),[20; 50),[10; 25),[60; 100),[4400; 9400)
2,Moderate,3,[80; 250),[70; 150),[50; 100),[25; 50),[100; 140),[9400; 12400)
3,Poor,4,[250; 350),[150; 200),[100; 200),[50; 75),[140; 180),[12400; 15400)
4,Very Poor,5,>350,>200,>200,>75,>180,>15400

In [9]:
import requests,json
from bs4 import BeautifulSoup
api="3b5a258fb2bb246eacb62e89cca5fa33"
def air_polution():
    api_key=api
    url=f"http://api.openweathermap.org/data/2.5/air_pollution?lat={x}&lon={y}&appid={api}"
    response=requests.get(url,verify=False)
    pollution=response.json()
    print(json.dumps(pollution,indent=5))
    return pollution
a=air_polution()

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "list": [
          {
               "main": {
                    "aqi": 2
               },
               "components": {
                    "co": 105.18,
                    "no": 0.16,
                    "no2": 0.81,
                    "o3": 75.71,
                    "so2": 1.78,
                    "pm2_5": 12.73,
                    "pm10": 40.92,
                    "nh3": 0.76
               },
               "dt": 1779779789
          }
     ]
}

# Call 5 day / 3 hour forecast data

In [10]:
import requests,json
from bs4 import BeautifulSoup
api="3b5a258fb2bb246eacb62e89cca5fa33"
def forecast():
    api_key=api
    url=f"https://api.openweathermap.org/data/2.5/forecast?lat={x}&lon={y}&appid={api}"
    response=requests.get(url,verify=False)
    forecast=response.json()
    print(json.dumps(forecast,indent=5))
    return forecast
a=forecast()

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779786000,
               "main": {
                    "temp": 310.67,
                    "feels_like": 312.09,
                    "temp_min": 310.67,
                    "temp_max": 315.62,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 999,
                    "humidity": 31,
                    "temp_kf": -4.95
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.87,
                    "deg": 251,
                    "gust": 5.29
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 09:00:00"
          },
          {
               "dt": 1779796800,
               "main": {
                    "temp": 313.4,
                    "feels_like": 313.9,
                    "temp_min": 313.4,
                    "temp_max": 316.01,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 998,
                    "humidity": 23,
                    "temp_kf": -2.61
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.66,
                    "deg": 266,
                    "gust": 5.44
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 12:00:00"
          },
          {
               "dt": 1779807600,
               "main": {
                    "temp": 308.33,
                    "feels_like": 310.4,
                    "temp_min": 308.33,
                    "temp_max": 308.33,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 39,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.12,
                    "deg": 209,
                    "gust": 7.94
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 15:00:00"
          },
          {
               "dt": 1779818400,
               "main": {
                    "temp": 305.21,
                    "feels_like": 309.48,
                    "temp_min": 305.21,
                    "temp_max": 305.21,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 57,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 2.92,
                    "deg": 221,
                    "gust": 5.11
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 18:00:00"
          },
          {
               "dt": 1779829200,
               "main": {
                    "temp": 303.21,
                    "feels_like": 306.51,
                    "temp_min": 303.21,
                    "temp_max": 303.21,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 62,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.95,
                    "deg": 264,
                    "gust": 7.15
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 21:00:00"
          },
          {
               "dt": 1779840000,
               "main": {
                    "temp": 302.65,
                    "feels_like": 305.42,
                    "temp_min": 302.65,
                    "temp_max": 302.65,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 62,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.78,
                    "deg": 275,
                    "gust": 8.53
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 00:00:00"
          },
          {
               "dt": 1779850800,
               "main": {
                    "temp": 305.03,
                    "feels_like": 307.29,
                    "temp_min": 305.03,
                    "temp_max": 305.03,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1004,
                    "humidity": 50,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5,
                    "deg": 248,
                    "gust": 6.75
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 03:00:00"
          },
          {
               "dt": 1779861600,
               "main": {
                    "temp": 311.79,
                    "feels_like": 312.04,
                    "temp_min": 311.79,
                    "temp_max": 311.79,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.14,
                    "deg": 255,
                    "gust": 6.63
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 06:00:00"
          },
          {
               "dt": 1779872400,
               "main": {
                    "temp": 316.06,
                    "feels_like": 314.79,
                    "temp_min": 316.06,
                    "temp_max": 316.06,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 15,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.63,
                    "deg": 258,
                    "gust": 5.7
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 09:00:00"
          },
          {
               "dt": 1779883200,
               "main": {
                    "temp": 316.33,
                    "feels_like": 314.75,
                    "temp_min": 316.33,
                    "temp_max": 316.33,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 14,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.11,
                    "deg": 286,
                    "gust": 6.26
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 12:00:00"
          },
          {
               "dt": 1779894000,
               "main": {
                    "temp": 306.8,
                    "feels_like": 310.79,
                    "temp_min": 306.8,
                    "temp_max": 306.8,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 50,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.78,
                    "deg": 190,
                    "gust": 7.99
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 15:00:00"
          },
          {
               "dt": 1779904800,
               "main": {
                    "temp": 305.67,
                    "feels_like": 308.49,
                    "temp_min": 305.67,
                    "temp_max": 305.67,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 50,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 2.79,
                    "deg": 237,
                    "gust": 5.23
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 18:00:00"
          },
          {
               "dt": 1779915600,
               "main": {
                    "temp": 302.94,
                    "feels_like": 306.17,
                    "temp_min": 302.94,
                    "temp_max": 302.94,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 63,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.68,
                    "deg": 261,
                    "gust": 9.16
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 21:00:00"
          },
          {
               "dt": 1779926400,
               "main": {
                    "temp": 302.78,
                    "feels_like": 305.29,
                    "temp_min": 302.78,
                    "temp_max": 302.78,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 60,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.03,
                    "deg": 265,
                    "gust": 8.89
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-28 00:00:00"
          },
          {
               "dt": 1779937200,
               "main": {
                    "temp": 304.97,
                    "feels_like": 307.66,
                    "temp_min": 304.97,
                    "temp_max": 304.97,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1004,
                    "humidity": 52,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.91,
                    "deg": 257,
                    "gust": 7.78
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-28 03:00:00"
          },
          {
               "dt": 1779948000,
               "main": {
                    "temp": 312.36,
                    "feels_like": 312.29,
                    "temp_min": 312.36,
                    "temp_max": 312.36,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 23,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.11,
                    "deg": 248,
                    "gust": 7.58
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-28 06:00:00"
          },
          {
               "dt": 1779958800,
               "main": {
                    "temp": 317.27,
                    "feels_like": 315.52,
                    "temp_min": 317.27,
                    "temp_max": 317.27,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 13,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.45,
                    "deg": 254,
                    "gust": 7.32
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-28 09:00:00"
          },
          {
               "dt": 1779969600,
               "main": {
                    "temp": 317.03,
                    "feels_like": 315.23,
                    "temp_min": 317.03,
                    "temp_max": 317.03,
                    "pressure": 1002,
                    "sea_level": 1002,
                    "grnd_level": 997,
                    "humidity": 13,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.8,
                    "deg": 279,
                    "gust": 7.68
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-28 12:00:00"
          },
          {
               "dt": 1779980400,
               "main": {

C:\ProgramData\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.251'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [11]:
date=[]
desc=[]
temp=[]
temp=[]
pressure=[]
humidity=[]
visibility=[]
windspeed=[]
for i in a["list"]:
    date.append(i["dt_txt"])
    desc.append(i["weather"][0]["description"])
    celsius_temp = i["main"]["temp"] - 273.15
    temp.append(round(celsius_temp, 2))    
    pressure.append(i["main"]["pressure"])
    humidity.append(i["main"]["humidity"])
    visibility.append(i["visibility"])
    windspeed.append(i["wind"]["speed"])
import pandas as pd

# 1. Create a dictionary pairing column names with your lists
weather_data = {
    "Date": date,
    "Description": desc,
    "Temperature (°C)": temp,
    "Pressure (hPa)": pressure,
    "Humidity (%)": humidity,
    "Visibility (m)": visibility,
    "Wind Speed (m/s)": windspeed
}

# 2. Create the DataFrame
df = pd.DataFrame(weather_data)
df

,Date,Description,Temperature (°C),Pressure (hPa),Humidity (%),Visibility (m),Wind Speed (m/s)
0,2026-05-26 09:00:00,clear sky,37.52,1007,31,10000,4.87
1,2026-05-26 12:00:00,clear sky,40.25,1005,23,10000,5.66
2,2026-05-26 15:00:00,clear sky,35.18,1006,39,10000,5.12
3,2026-05-26 18:00:00,clear sky,32.06,1007,57,10000,2.92
4,2026-05-26 21:00:00,clear sky,30.06,1006,62,10000,3.95
5,2026-05-27 00:00:00,clear sky,29.50,1007,62,10000,4.78
6,2026-05-27 03:00:00,clear sky,31.88,1009,50,10000,5.00
7,2026-05-27 06:00:00,clear sky,38.64,1008,25,10000,5.14
8,2026-05-27 09:00:00,clear sky,42.91,1005,15,10000,5.63
9,2026-05-27 12:00:00,clear sky,43.18,1003,14,10000,6.11
10,2026-05-27 15:00:00,clear sky,33.65,1006,50,10000,5.78
11,2026-05-27 18:00:00,clear sky,32.52,1008,50,10000,2.79
12,2026-05-27 21:00:00,clear sky,29.79,1006,63,10000,4.68
13,2026-05-28 00:00:00,clear sky,29.63,1007,60,10000,5.03
14,2026-05-28 03:00:00,clear sky,31.82,1009,52,10000,5.91
15,2026-05-28 06:00:00,clear sky,39.21,1007,23,10000,6.11
16,2026-05-28 09:00:00,clear sky,44.12,1004,13,10000,6.45
17,2026-05-28 12:00:00,clear sky,43.88,1002,13,10000,6.80
18,2026-05-28 15:00:00,clear sky,34.63,1005,40,10000,4.84
19,2026-05-28 18:00:00,clear sky,31.63,1006,46,10000,4.48
20,2026-05-28 21:00:00,clear sky,30.98,1006,54,10000,5.56
21,2026-05-29 00:00:00,clear sky,29.15,1007,66,10000,5.40
22,2026-05-29 03:00:00,clear sky,31.53,1008,53,10000,7.25
23,2026-05-29 06:00:00,clear sky,38.62,1006,26,10000,7.62
24,2026-05-29 09:00:00,clear sky,42.80,1003,17,10000,8.09
25,2026-05-29 12:00:00,clear sky,42.66,1001,17,10000,7.96
26,2026-05-29 15:00:00,clear sky,34.52,1003,36,10000,8.32
27,2026-05-29 18:00:00,clear sky,32.74,1003,46,10000,5.63
28,2026-05-29 21:00:00,clear sky,29.88,1003,61,10000,6.87
29,2026-05-30 00:00:00,clear sky,28.57,1004,70,10000,6.54
30,2026-05-30 03:00:00,clear sky,31.46,1005,56,10000,7.80
31,2026-05-30 06:00:00,clear sky,38.12,1003,32,10000,8.71
32,2026-05-30 09:00:00,clear sky,42.62,1000,21,10000,8.71
33,2026-05-30 12:00:00,clear sky,41.70,999,22,10000,8.73
34,2026-05-30 15:00:00,clear sky,36.90,1001,34,10000,7.02
35,2026-05-30 18:00:00,clear sky,32.12,1003,53,10000,7.99
36,2026-05-30 21:00:00,clear sky,29.84,1003,67,10000,6.17
37,2026-05-31 00:00:00,clear sky,29.03,1003,71,10000,5.30
38,2026-05-31 03:00:00,broken clouds,31.17,1005,58,10000,6.94
39,2026-05-31 06:00:00,scattered clouds,37.36,1004,35,10000,6.24